name: grii1
favicon: null
layout_spectrum: 0.4689822718501091
typography_spectrum: 0.825040050316602
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.37423473759554327
  lightness: 0.4460665564984083
  saturation: 0.5680214252788574
  rhythmicContrast: 0.3145831534639001
purpose: []
